#
# Required environment variables in the travis config
#
# DOCKER_USERNAME
#
language: cpp
cache: ccache

git:
  submodules: false

env:
  global:
    - QT_INSTALL_DIR=~/Qt
    - QT_VERSION=5.12.6
    - QTCREATOR_VERSION=4.10.2

stages:
  - name: Build Qbs and and run autotests

jobs:
  include:
    - &build-on-windows
      stage: Build Qbs and and run autotests
      name: With Qbs on Windows (Visual Studio 2017)
      os: windows
      services: docker
      env:
        # Need to build in release mode. Otherwise autotests would be too slow.
        BUILD_OPTIONS="config:release modules.cpp.compilerWrapper:clcache"
        QMAKE_PATH=${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017_64/bin/qmake.exe
        PATH="${QT_INSTALL_DIR}/Tools/QtCreator/bin:/c/Python38:/c/Python39:/c/Python38/Scripts:/c/Python39/Scripts:${PATH}"
        QBS_BUILD_PROFILE=qt
      before_install:
        - curl -sLo "/c/Program Files/Docker/docker-compose.exe" https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Windows-x86_64.exe
        # Todo remove
        - docker-compose build windows
      before_script:
        - docker-compose run --rm windows clcache -s
      script:
        - docker-compose run --rm windows bash -c ./scripts/build-qbs-with-qbs.sh ${BUILD_OPTIONS}
      after_script:
        - docker-compose run --rm windows clcache -s