version: "3.7"

x-default-service: &linux
  working_dir: /qbs
  environment:
    - BUILD_OPTIONS
    - QTEST_FUNCTION_TIMEOUT
    - QBS_AUTOTEST_PROFILE
  volumes:
    - .:/qbs
    - ~/.ccache:/home/devel/.ccache
  network_mode: bridge
  cap_add:
      - SYS_PTRACE

services:
  bionic:
    << : *linux
    hostname: bionic
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-5.15.0_1.15.1-2
    build:
      dockerfile: docker/bionic/Dockerfile
      context: .
      args:
        QT_VERSION: 5.15.0
        QTCREATOR_VERSION: 4.11.2

  bionic-android-513:
    << : *linux
    hostname: bionic-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-android-5.13.2-3
    build:
      dockerfile: docker/bionic/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.13.2

  bionic-android-514:
    << : *linux
    hostname: bionic-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-android-5.14.0-3
    build:
      dockerfile: docker/bionic/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.14.0

  focal-baremetal:
    << : *linux
    hostname: focal-baremetal
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:focal-baremetal-0
    build:
      dockerfile: docker/focal/test-baremetal.Dockerfile
      context: .

  windows:
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:windowsservercore-5.15.0_1.16.0-0
    build:
      dockerfile: docker/windowsservercore/Dockerfile
      context: .
      args:
        QT_VERSION: 5.15.0
        QBS_VERSION: 1.16.0
    working_dir: 'C:/qbs'
    environment:
      - BUILD_OPTIONS
      - WITH_DOCS
    volumes:
      - .:C:\qbs
      - ~/.ccache:C:\.ccache
    network_mode: nat
